//===- SolCanonicalization.td - Sol dialect canon ----------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_SOL_SOLCANONICALIZATION_TD
#define MLIR_DIALECT_SOL_SOLCANONICALIZATION_TD

include "SolOps.td"
include "mlir/IR/PatternBase.td"

#endif // MLIR_DIALECT_SOL_SOLCANONICALIZATION_TD
