# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -x mir -run-pass=evm-backward-propagation-stackification -verify-machineinstrs < %s | FileCheck %s

# Test that stackification runs successfully on a function with implicit defs in the entry block.
# IMPLICIT_DEF will be stackified to PUSH0.

--- |
  target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
  target triple = "evm-unknown-unknown"

  declare i256 @llvm.evm.chainid() #0

  define void @test(i256 %cond) {
  entry:
    ret void
  }

  attributes #0 = { nocallback nounwind willreturn memory(inaccessiblemem: read) }

...
---
name:            test
alignment:       1
tracksRegLiveness: true
liveins:
  - { reg: '$value_stack', virtual-reg: '' }
machineFunctionInfo:
  isStackified:    false
  numberOfParameters: 1
  hasPushDeployAddress: false
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments, $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PUSH0_S
  ; CHECK-NEXT:   SWAP1_S
  ; CHECK-NEXT:   PseudoJUMP_UNLESS %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PUSH0_S
  ; CHECK-NEXT:   PseudoJUMP %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   POP_S
  ; CHECK-NEXT:   CHAINID_S
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PUSH1_S i256 1
  ; CHECK-NEXT:   PseudoJUMP %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x00000800), %bb.8(0x7ffff800)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PUSH1_S i256 1
  ; CHECK-NEXT:   DUP2_S
  ; CHECK-NEXT:   XOR_S
  ; CHECK-NEXT:   PseudoJUMPI %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   POP_S
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   POP_S
  ; CHECK-NEXT:   PUSH0_S
  ; CHECK-NEXT:   PseudoJUMP %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJUMP_UNLESS %bb.2
  ; CHECK-NEXT:   PseudoJUMP %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PUSH0_S
  ; CHECK-NEXT:   PseudoJUMP %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT:   liveins: $value_stack
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PUSH1_S i256 1
  ; CHECK-NEXT:   PseudoJUMP %bb.7
  bb.0:
    successors: %bb.1(0x40000000), %bb.6(0x40000000)
    liveins: $arguments, $value_stack

    %0:gpr = ARGUMENT 0, implicit $arguments
    %1:gpr = IMPLICIT_DEF
    JUMP_UNLESS %bb.6, %0, implicit-def $arguments

  bb.1:
    successors: %bb.7(0x80000000)
    liveins: $value_stack

    %7:gpr = CONST_I256 i256 0, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments

  bb.2:
    successors: %bb.3(0x80000000)
    liveins: $value_stack

    %1:gpr = CHAINID implicit-def dead $arguments

  bb.3:
    successors: %bb.7(0x80000000)
    liveins: $value_stack

    %7:gpr = CONST_I256 i256 1, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments

  bb.4:
    successors: %bb.5(0x00000800), %bb.8(0x7ffff800)
    liveins: $value_stack

    %5:gpr = CONST_I256 i256 1, implicit-def dead $arguments, implicit-def $value_stack, implicit $value_stack
    %6:gpr = XOR %1, %5, implicit-def dead $arguments, implicit-def $value_stack, implicit $value_stack
    JUMPI %bb.8, %6, implicit-def $arguments, implicit-def $value_stack, implicit $value_stack

  bb.5:
    liveins: $value_stack

    RET implicit-def dead $arguments

  bb.6:
    successors: %bb.9(0x80000000)
    liveins: $value_stack

    %1:gpr = CONST_I256 i256 0, implicit-def dead $arguments
    JUMP %bb.9, implicit-def $arguments

  bb.7:
    successors: %bb.2(0x40000000), %bb.4(0x40000000)
    liveins: $value_stack

    JUMP_UNLESS %bb.2, %7, implicit-def $arguments
    JUMP %bb.4, implicit-def $arguments

  bb.8:
    successors: %bb.7(0x80000000)
    liveins: $value_stack

    %7:gpr = CONST_I256 i256 0, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments

  bb.9:
    successors: %bb.7(0x80000000)
    liveins: $value_stack

    %7:gpr = CONST_I256 i256 1, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments
...
