# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -x mir -run-pass=evm-fix-irreducible-control-flow -verify-machineinstrs < %s | FileCheck %s

# Test that we are not failing liveness verification, as we added IMPLICIT_DEF instructions
# in the entry BB.

--- |
  target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
  target triple = "evm-unknown-unknown"

  declare i256 @llvm.evm.chainid() #0

  define void @irreducible_needs_fallback(i256 %cond) {
  entry:
    ret void
  }

  attributes #0 = { mustprogress nocallback nofree nounwind willreturn memory(inaccessiblemem: read) }

...
---
name:            irreducible_needs_fallback
alignment:       1
tracksRegLiveness: true
isSSA:           false
machineFunctionInfo:
  isStackified:    false
  numberOfParameters: 1
  hasPushDeployAddress: false
body:             |
  ; CHECK-LABEL: name: irreducible_needs_fallback
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT:%[0-9]+]]:gpr = ARGUMENT 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   JUMP_UNLESS %bb.6, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CHAINID implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x00000800), %bb.8(0x7ffff800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def dead $arguments
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = XOR [[DEF]], [[DEF1]], implicit-def dead $arguments
  ; CHECK-NEXT:   JUMPI %bb.8, [[DEF2]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   RET implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def dead $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.2, [[DEF3]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.4, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  bb.0:
    liveins: $arguments
    successors: %bb.1(0x40000000), %bb.4(0x40000000)

    %0:gpr = ARGUMENT 0, implicit $arguments
    JUMP_UNLESS %bb.4, %0, implicit-def $arguments

  bb.1:
    successors: %bb.2(0x80000000)

    %1:gpr = CHAINID implicit-def dead $arguments

  bb.2:
    successors: %bb.3(0x00000800), %bb.1(0x7ffff800)

    %2:gpr = CONST_I256 i256 1, implicit-def dead $arguments
    %3:gpr = XOR %1, %2, implicit-def dead $arguments
    JUMPI %bb.1, %3, implicit-def $arguments

  bb.3:
    RET implicit-def dead $arguments

  bb.4:
    successors: %bb.2(0x80000000)

    %1:gpr = CONST_I256 i256 0, implicit-def dead $arguments
    JUMP %bb.2, implicit-def $arguments

...
