# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -x mir -run-pass=evm-fix-irreducible-control-flow -verify-machineinstrs < %s | FileCheck %s

--- |
  target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
  target triple = "evm-unknown-unknown"

  declare i256 @llvm.evm.chainid() #0

  define void @irreducible_2_entry(i256 %cond) {
  entry:
    ret void
  }

  define void @irreducible_3_entry(i256 %cond) {
  entry:
    ret void
  }

  define void @irreducible_nested(i256 %cond) {
  entry:
    ret void
  }

  define void @irreducible_parent_rewrites_child_entry(i256 %cond) {
  entry:
    ret void
  }

  attributes #0 = { mustprogress nocallback nofree nounwind willreturn memory(inaccessiblemem: read) }

...

# Test an irreducible CFG with 2 entries.

---
name:            irreducible_2_entry
alignment:       1
tracksRegLiveness: true
isSSA:           false
body:             |
  ; CHECK-LABEL: name: irreducible_2_entry
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT:%[0-9]+]]:gpr = ARGUMENT i256 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def dead $arguments
  ; CHECK-NEXT:   JUMP_UNLESS %bb.7, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CHAINID implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x00000800), %bb.8(0x7ffff800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def dead $arguments
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = XOR [[DEF]], [[DEF1]], implicit-def dead $arguments
  ; CHECK-NEXT:   JUMPI %bb.8, [[DEF2]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   PseudoRET implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.2, [[DEF3]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.4, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  bb.0:
    liveins: $arguments
    successors: %bb.1(0x40000000), %bb.2(0x40000000)

    %0:gpr = ARGUMENT i256 0, implicit $arguments
    %1:gpr = CONST_I256 i256 0, implicit-def dead $arguments
    JUMP_UNLESS %bb.2, %0, implicit-def $arguments

  bb.1:
    successors: %bb.2(0x80000000)

    %1:gpr = CHAINID implicit-def dead $arguments

  bb.2:
    successors: %bb.3(0x00000800), %bb.1(0x7ffff800)

    %2:gpr = CONST_I256 i256 1, implicit-def dead $arguments
    %3:gpr = XOR %1, %2, implicit-def dead $arguments
    JUMPI %bb.1, %3, implicit-def $arguments

  bb.3:
    PseudoRET implicit-def $arguments

...

# Test an irreducible CFG with 3 entries.

---
name:            irreducible_3_entry
alignment:       1
tracksRegLiveness: true
isSSA:           false
body:             |
  ; CHECK-LABEL: name: irreducible_3_entry
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT:%[0-9]+]]:gpr = ARGUMENT i256 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   JUMP_UNLESS %bb.7, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CHAINID:%[0-9]+]]:gpr = CHAINID implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CONST_I256_:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 2, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.8(0x00000800), %bb.11(0x7ffff800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMPI %bb.11, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.8, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.12(0x40000000), %bb.13(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.13, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.12, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   PseudoRET implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.2, [[DEF]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = EQ [[DEF]], [[DEF1]], implicit-def $arguments
  ; CHECK-NEXT:   JUMPI %bb.4, [[DEF2]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.11:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.12:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.13:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 2, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  bb.0:
    liveins: $arguments
    successors: %bb.1(0x40000000), %bb.4(0x40000000)

    %0:gpr = ARGUMENT i256 0, implicit $arguments
    JUMP_UNLESS %bb.4, %0, implicit-def $arguments

  bb.1:
    successors: %bb.2(0x80000000)

    %1:gpr = CHAINID implicit-def dead $arguments

  bb.2:
    successors: %bb.3(0x80000000)

    %2:gpr = CONST_I256 i256 1, implicit-def dead $arguments

  bb.3:
    successors: %bb.5(0x00000800), %bb.1(0x7ffff800)

    JUMPI %bb.1, %0, implicit-def $arguments
    JUMP %bb.5, implicit-def $arguments

  bb.4:
    successors: %bb.2(0x40000000), %bb.3(0x40000000)

    JUMP_UNLESS %bb.3, %0, implicit-def $arguments
    JUMP %bb.2, implicit-def $arguments

  bb.5:
    PseudoRET implicit-def $arguments

...

# Test nested irreducibility: both the outer and inner cycles need repairs.

---
name:            irreducible_nested
alignment:       1
tracksRegLiveness: true
isSSA:           false
body:             |
  ; CHECK-LABEL: name: irreducible_nested
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.12(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT:%[0-9]+]]:gpr = ARGUMENT i256 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def dead $arguments
  ; CHECK-NEXT:   JUMP_UNLESS %bb.12, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.11, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.10(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.10, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.11, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.15(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.15, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.14(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.14, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CHAINID implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.14(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.14, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.16(0x40000000), %bb.9(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def dead $arguments
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:gpr = XOR [[DEF]], [[DEF1]], implicit-def dead $arguments
  ; CHECK-NEXT:   JUMPI %bb.16, [[DEF2]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.13(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP %bb.13, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10:
  ; CHECK-NEXT:   PseudoRET implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.11:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.2, [[DEF3]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.4, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.12:
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.11, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.13:
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.11, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.14:
  ; CHECK-NEXT:   successors: %bb.6(0x40000000), %bb.8(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.6, [[DEF4]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.8, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.15:
  ; CHECK-NEXT:   successors: %bb.14(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.14, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.16:
  ; CHECK-NEXT:   successors: %bb.14(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.14, implicit-def $arguments
  bb.0:
    liveins: $arguments
    successors: %bb.1(0x40000000), %bb.2(0x40000000)

    %0:gpr = ARGUMENT i256 0, implicit $arguments
    %1:gpr = CONST_I256 i256 0, implicit-def dead $arguments
    JUMP_UNLESS %bb.2, %0, implicit-def $arguments

  bb.1:
    successors: %bb.6(0x40000000), %bb.2(0x40000000)

    JUMP_UNLESS %bb.6, %0, implicit-def $arguments

  bb.2:
    successors: %bb.4(0x40000000), %bb.3(0x40000000)

    JUMP_UNLESS %bb.4, %0, implicit-def $arguments

  bb.3:
    successors: %bb.4(0x80000000)

    %1:gpr = CHAINID implicit-def dead $arguments

  bb.4:
    successors: %bb.3(0x40000000), %bb.5(0x40000000)

    %2:gpr = CONST_I256 i256 1, implicit-def dead $arguments
    %3:gpr = XOR %1, %2, implicit-def dead $arguments
    JUMPI %bb.3, %3, implicit-def $arguments

  bb.5:
    successors: %bb.1(0x80000000)

    JUMP %bb.1, implicit-def $arguments

  bb.6:
    PseudoRET implicit-def $arguments

...

# Test in which an outer irreducible cycle contains an irreducible child cycle
# whose entry is also an entry of the parent cycle.
# This test exposes issue when using CycleAnalysis and updating it on the fly
# as FixIrreducible.cpp does, in which case assert inside CycleAnalysis fails.

---
name:            irreducible_parent_rewrites_child_entry
alignment:       1
tracksRegLiveness: true
isSSA:           false
body:             |
  ; CHECK-LABEL: name: irreducible_parent_rewrites_child_entry
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT:%[0-9]+]]:gpr = ARGUMENT i256 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   JUMP_UNLESS %bb.7, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMPI %bb.4, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.5, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMPI %bb.4, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.5, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP %bb.8, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.2, [[DEF]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.3, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.6, implicit-def $arguments

  bb.0:
    liveins: $arguments
    successors: %bb.1(0x40000000), %bb.2(0x40000000)

    %0:gpr = ARGUMENT i256 0, implicit $arguments
    JUMP_UNLESS %bb.2, %0, implicit-def $arguments

  bb.1:
    successors: %bb.3(0x40000000), %bb.4(0x40000000)

    JUMPI %bb.3, %0, implicit-def $arguments
    JUMP %bb.4, implicit-def $arguments

  bb.2:
    successors: %bb.3(0x40000000), %bb.4(0x40000000)

    JUMPI %bb.3, %0, implicit-def $arguments
    JUMP %bb.4, implicit-def $arguments

  bb.3:
    successors: %bb.1(0x80000000)

    JUMP %bb.1, implicit-def $arguments

  bb.4:
    successors: %bb.2(0x80000000)

    JUMP %bb.2, implicit-def $arguments

...
