; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=memcpyopt < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define void @test_storage() {
; CHECK-LABEL: define void @test_storage() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.memset.p5.i64(ptr addrspace(5) align 1 null, i8 0, i64 32, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  store i256 0, ptr addrspace(5) null, align 1
  store i256 0, ptr addrspace(5) null, align 1
  ret void
}

define void @test_heap() {
; CHECK-LABEL: define void @test_heap() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.memset.p1.i64(ptr addrspace(1) align 1 null, i8 0, i64 32, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  store i256 0, ptr addrspace(1) null, align 1
  store i256 0, ptr addrspace(1) null, align 1
  ret void
}
