# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -x mir -run-pass=evm-optimize-live-intervals -verify-machineinstrs < %s | FileCheck %s

# Test that EVMOptimizeLiveIntervals correctly removes dead implicit defs and leaves
# ones that are live.

--- |
  target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
  target triple = "evm-unknown-unknown"

  declare i256 @llvm.evm.chainid() #0

  define void @test(i256 %cond) {
  entry:
    ret void
  }

  attributes #0 = { nocallback nounwind willreturn memory(inaccessiblemem: read) }

...
---
name:            test
alignment:       1
tracksRegLiveness: true
machineFunctionInfo:
  isStackified:    false
  numberOfParameters: 1
  hasPushDeployAddress: false
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT:%[0-9]+]]:gpr = ARGUMENT 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   JUMP_UNLESS %bb.6, [[ARGUMENT]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CONST_I256_:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CHAINID implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CONST_I256_:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x00000800), %bb.8(0x7ffff800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CONST_I256_1:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def dead $arguments
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:gpr = XOR [[DEF]], [[CONST_I256_1]], implicit-def dead $arguments
  ; CHECK-NEXT:   JUMPI %bb.8, [[XOR]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   RET implicit-def dead $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def dead $arguments
  ; CHECK-NEXT:   JUMP %bb.9, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JUMP_UNLESS %bb.2, [[CONST_I256_]], implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.4, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CONST_I256_:%[0-9]+]]:gpr = CONST_I256 i256 0, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CONST_I256_:%[0-9]+]]:gpr = CONST_I256 i256 1, implicit-def $arguments
  ; CHECK-NEXT:   JUMP %bb.7, implicit-def $arguments
  bb.0:
    successors: %bb.1(0x40000000), %bb.6(0x40000000)
    liveins: $arguments

    %0:gpr = ARGUMENT 0, implicit $arguments
    %1:gpr = IMPLICIT_DEF
    %2:gpr = IMPLICIT_DEF
    %3:gpr = IMPLICIT_DEF
    %4:gpr = IMPLICIT_DEF
    JUMP_UNLESS %bb.6, %0, implicit-def $arguments

  bb.1:
    successors: %bb.7(0x80000000)

    %4:gpr = CONST_I256 i256 0, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments

  bb.2:
    successors: %bb.3(0x80000000)

    %1:gpr = CHAINID implicit-def dead $arguments

  bb.3:
    successors: %bb.7(0x80000000)

    %4:gpr = CONST_I256 i256 1, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments

  bb.4:
    successors: %bb.5(0x00000800), %bb.8(0x7ffff800)

    %2:gpr = CONST_I256 i256 1, implicit-def dead $arguments
    %3:gpr = XOR %1, %2, implicit-def dead $arguments
    JUMPI %bb.8, %3, implicit-def $arguments

  bb.5:
    RET implicit-def dead $arguments

  bb.6:
    successors: %bb.9(0x80000000)

    %1:gpr = CONST_I256 i256 0, implicit-def dead $arguments
    JUMP %bb.9, implicit-def $arguments

  bb.7:
    successors: %bb.2(0x40000000), %bb.4(0x40000000)

    JUMP_UNLESS %bb.2, %4, implicit-def $arguments
    JUMP %bb.4, implicit-def $arguments

  bb.8:
    successors: %bb.7(0x80000000)

    %4:gpr = CONST_I256 i256 0, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments

  bb.9:
    successors: %bb.7(0x80000000)

    %4:gpr = CONST_I256 i256 1, implicit-def $arguments
    JUMP %bb.7, implicit-def $arguments
...
