//===- EVMUtil.h - EVM specific MLIR utilities ------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares EVM-specific MLIR utilities.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_CONVERSION_SOLTOSTANDARD_EVMUTIL_H
#define MLIR_CONVERSION_SOLTOSTANDARD_EVMUTIL_H

#include "mlir/Conversion/SolToStandard/EVMConstants.h"
#include "mlir/Dialect/Sol/Sol.h"
#include "mlir/IR/Builders.h"
#include "llvm/ADT/APInt.h"
#include <optional>

namespace mlir {
namespace evm {

enum AddrSpace : unsigned {
  AddrSpace_Stack = 0,
  AddrSpace_Heap = 1,
  AddrSpace_CallData = 2,
  AddrSpace_ReturnData = 3,
  AddrSpace_Code = 4,
  AddrSpace_Storage = 5,
  AddrSpace_TransientStorage = 6,
};

enum ByteLen {
  ByteLen_Byte = 1,
  ByteLen_X32 = 4,
  ByteLen_X64 = 8,
  ByteLen_EthAddr = 20,
  ByteLen_Field = 32
};

using AllocSize = int64_t;

/// Returns the alignment of `addrSpace`
unsigned getAlignment(AddrSpace addrSpace);
/// Returns the alignment of the LLVMPointerType value `ptr`
unsigned getAlignment(Value ptr);

// FIXME: Remove this! The lowering should not expand the ABI encoding/decoding
// code (where this is used) involved in sol.contract, sol.emit etc. lowering.
// Instead it should generate a high level sol op that can have a custom
// lowering for each target.
/// MLIR version of solidity ast's Type::calldataHeadSize.
unsigned getCallDataHeadSize(Type ty);

/// Returns the size (in bytes) of static type without recursively calculating
/// the element type size.
int64_t getMallocSize(Type ty);

/// MLIR version of solidity ast's Type::storageSize().
unsigned getStorageSlotCount(Type ty);

/// Returns true if the type can be packed within a storage slot.
/// Packable types (scalars) need {slot, offset} representation.
/// Non-packable types (arrays, structs, mappings) are slot-aligned and only
/// need slot.
bool canBePacked(mlir::Type ty);

/// Returns the byte size of a packable type in storage.
unsigned getStorageByteSize(mlir::Type ty);

/// IR Builder for EVM specific lowering.
class Builder {
  // It's possible to provide a mlirgen::BuilderHelper member with same default
  // location, but then it becomes tricky to keep the default location behaviour
  // consistent.

  OpBuilder &b;
  Location defLoc;

public:
  explicit Builder(OpBuilder &b) : b(b), defLoc(b.getUnknownLoc()) {}

  explicit Builder(OpBuilder &b, Location loc) : b(b), defLoc(loc) {}

  /// Generates a pointer to the address in the heap.
  Value genHeapPtr(Value addr, std::optional<Location> locArg = std::nullopt);

  /// Generates a pointer to the address in the calldata.
  Value genCallDataPtr(Value addr,
                       std::optional<Location> locArg = std::nullopt);

  /// Generates a pointer to the address in the returndata.
  Value genReturnDataPtr(Value addr,
                         std::optional<Location> locArg = std::nullopt);

  /// Generates a pointer to the address in the storage.
  Value genStoragePtr(Value addr,
                      std::optional<Location> locArg = std::nullopt);

  /// Generates a pointer to the address in the transient storage.
  Value genTStoragePtr(Value addr,
                       std::optional<Location> locArg = std::nullopt);

  /// Generates a pointer to the address in the code.
  Value genCodePtr(Value addr, std::optional<Location> locArg = std::nullopt);

  //
  // The following APIs are used in the stage1 lowering.
  //
  // TODO? Some of these could be transformed to mlir ops instead. This would
  // allow targets to define custom lowering. For instance, some targets might
  // not need the `type(uint64).max` check in the memory allocation code
  // generated by the genMemAlloc APIs.
  //

  /// Generates the free pointer.
  ///
  /// NOTE! Watch out for free-ptr loads between this and the update!
  Value genFreePtr(std::optional<Location> locArg = std::nullopt);

  /// Generates the free pointer update code.
  void genFreePtrUpd(Value freePtr, Value size,
                     std::optional<Location> locArg = std::nullopt);

  /// Generates the memory allocation code.
  Value genMemAlloc(Value size, std::optional<Location> locArg = std::nullopt);
  Value genMemAlloc(AllocSize size,
                    std::optional<Location> locArg = std::nullopt);

  /// Generates the memory allocation code for dynamic array.
  Value genMemAllocForDynArray(Value sizeVar, Value sizeInBytes,
                               std::optional<Location> locArg = std::nullopt);

  /// Generates the memory allocation code.
  Value genMemAlloc(Type ty, bool zeroInit, ValueRange initVals, Value sizeVar,
                    std::optional<Location> locArg = std::nullopt);

private:
  Value genMemAlloc(Type ty, bool zeroInit, ValueRange initVals, Value sizeVar,
                    int64_t recDepth,
                    std::optional<Location> locArg = std::nullopt);

  /// Returns a normalized scalar value for ABI encoding and emits range checks
  /// to match Yul cleanup/validator behavior.
  Value normalizeABIScalarForEncoding(
      Type ty, Value val, Location loc,
      std::optional<sol::DataLocation> srcDataLoc = std::nullopt);

public:
  //
  // TODO? Should we work with the high level types + OpAdaptor for the APIs
  // that work with low level integral type pointers?
  //

  /// Generates a low level integral type pointer to the address holding the
  /// data of a dynamic allocation.
  Value genDataAddrPtr(Value addr, Type ty,
                       std::optional<Location> locArg = std::nullopt);
  Value genDataAddrPtr(Value addr, sol::DataLocation dataLoc,
                       std::optional<Location> locArg = std::nullopt);

  /// Generates the address computation of the array or string at index.
  // TODO: Data-location should be fetched from the type! Implement APIs to
  // "clone" reference types with different data-locations.
  Value genAddrAtIdx(Value baseAddr, Value idx, Type ty,
                     sol::DataLocation dataLoc,
                     std::optional<Location> locArg = std::nullopt);

  /// Generates {slot, offset} for packed storage array indexing.
  Value genPackedStorageAddr(Value baseSlot, Value idx, Type eltTy,
                             bool isDataLeftAligned = false,
                             std::optional<Location> locArg = std::nullopt);

  /// Loads slot and punches hole: and(sload/tload(slot), holeMask)
  /// where holeMask = not(ones(numBits) << shiftBits)
  Value genPunchHole(Value slot, Value shiftBits, unsigned numBits,
                     sol::DataLocation dataLoc = sol::DataLocation::Storage,
                     std::optional<Location> locArg = std::nullopt);

  /// Inserts integer value (<=32 bytes) to the slot value:
  /// or(and(slot, holeMask), shiftedVal), where
  /// holeMask = not(ones(numBits) << offset * 8),
  /// shiftedVal = (intVal << offset * 8)
  Value genInsertIntToSlot(Value slot, Value offset, Value intVal,
                           unsigned numBits, std::optional<Location> locArg);

  /// Generates a load from the low level integral type address.
  Value genLoad(Value addr, sol::DataLocation dataLoc,
                std::optional<Location> locArg = std::nullopt);

  /// Generates a size load from addr of dynamic type.
  Value genDynSize(Value addr, Type ty,
                   std::optional<Location> locArg = std::nullopt);

  /// Generates a store to the low level integral type address.
  void genStore(Value val, Value addr, sol::DataLocation dataLoc,
                std::optional<Location> locArg = std::nullopt);

  /// Generates the store of string at address.
  void genStringStore(std::string const &str, Value addr,
                      std::optional<Location> locArg = std::nullopt);

  /// Generates length of a string.
  mlir::Value
  genStringLength(mlir::Value lengthSlot, mlir::sol::DataLocation dataLoc,
                  std::optional<mlir::Location> locArg = std::nullopt);

  /// Copies string data from storage into an already-allocated memory data
  /// area \p dstDataAddr (i.e. the address past the length word). Does not
  /// write the length word. Use genCopyStringToMemory() to write both the
  /// data and the length word at a fresh memory allocation.
  void genCopyStringDataToMemory(
      mlir::Value srcDataAddr, mlir::Value lengthSlot, mlir::Value length,
      mlir::Value dstDataAddr,
      std::optional<mlir::Location> locArg = std::nullopt);

  /// Copies a string from storage to memory, including the length word.
  void
  genCopyStringToMemory(mlir::Value srcDataAddr, mlir::Value lengthSlot,
                        mlir::Value length, mlir::Value dstAddr,
                        std::optional<mlir::Location> locArg = std::nullopt);

  /// Copies a string to the storage.
  void
  genCopyStringToStorage(mlir::Value srcDataAddr, mlir::Value lengthSlot,
                         mlir::Value length, mlir::Value dstAddr,
                         mlir::sol::DataLocation srcDataLoc,
                         std::optional<mlir::Location> locArg = std::nullopt);

  /// Copies an object of type \p ty from \p srcAddr to \p dstAddr.
  void genCopy(mlir::Type ty, mlir::Value srcAddr, mlir::Value dstAddr,
               mlir::sol::DataLocation srcDataLoc,
               mlir::sol::DataLocation dstDataLoc,
               std::optional<mlir::Location> locArg = std::nullopt);

  /// Generates the 'push' of a value to string.
  void genPushToString(mlir::Value srcAddr, mlir::Value value,
                       std::optional<mlir::Location> locArg = std::nullopt);

  /// Generates the 'push' of a default value to string and
  /// returns a fat pointer to the newly added element.
  Value
  genPushVoidToString(Value srcAddr,
                      std::optional<mlir::Location> locArg = std::nullopt);

  /// Generates the 'pop' for string.
  void genPopString(mlir::Value srcAddr, mlir::Value oldData,
                    mlir::Value length,
                    std::optional<mlir::Location> locArg = std::nullopt);

  /// Generates {slot, offset} for string storage indexing.
  Value genStringItemAddress(mlir::Value srcAddr, mlir::Value idx,
                             std::optional<Location> locArg = std::nullopt);

  /// Generates an assertion that the tuple size should be less than `size`.
  void genABITupleSizeAssert(TypeRange tys, Value size,
                             std::optional<Location> locArg = std::nullopt);

  /// Generates the tuple encoder code as per the ABI and return the new tail
  /// address.
  Value genABITupleEncoding(
      Type ty, Value src, Value dstAddr, bool dstAddrInTail, Value tupleStart,
      Value tailAddr, std::optional<Location> locArg = std::nullopt,
      std::optional<sol::DataLocation> srcDataLoc = std::nullopt);

  /// Generates the tuple encoder code as per the ABI and returns the address at
  /// the end of the tuple.
  Value genABITupleEncoding(TypeRange tys, ValueRange vals, Value tupleStart,
                            std::optional<Location> locArg = std::nullopt);
  Value genABITupleEncoding(std::string const &str, Value headStart,
                            std::optional<Location> locArg = std::nullopt);

  Value genABITupleDecoding(Type ty, Value addr, bool fromMem, Value tupleStart,
                            Value tupleEnd,
                            std::optional<Location> locArg = std::nullopt);

  /// Generates the tuple decoder code as per the ABI and populates the results.
  void genABITupleDecoding(TypeRange tys, Value tupleStart, Value tupleEnd,
                           std::vector<Value> &results, bool fromMem,
                           std::optional<Location> locArg = std::nullopt);

  /// Generates packed (non-padded) encoding for a single value and returns the
  /// address after the encoded bytes.
  Value genABIPackedEncoding(Type ty, Value val, Value addr,
                             std::optional<Location> locArg = std::nullopt);

  /// Generates packed (non-padded) encoding for a tuple of values and returns
  /// the address after all encoded bytes.
  Value genABIPackedEncoding(TypeRange tys, ValueRange vals, Value addr,
                             std::optional<Location> locArg = std::nullopt);

  /// Generates the panic code.
  void genPanic(PanicCode code, std::optional<Location> locArg = std::nullopt);
  void genPanic(PanicCode code, Value cond,
                std::optional<Location> locArg = std::nullopt);

  /// Generates a revert with message.
  void genRevertWithMsg(std::string const &msg,
                        std::optional<Location> locArg = std::nullopt);
  void genRevertWithMsg(Value cond, std::string const &msg,
                        std::optional<Location> locArg = std::nullopt);

  /// Generates a forwarding revert.
  void genForwardingRevert(std::optional<Location> locArg = std::nullopt);
  void genForwardingRevert(Value cond,
                           std::optional<Location> locArg = std::nullopt);

  /// Generates a revert without message.
  void genRevert(Value cond, std::optional<Location> locArg = std::nullopt);

  /// Generates a revert with the abi encoded args.
  void genRevert(Value cond, TypeRange tys, ValueRange vals,
                 StringRef signature,
                 std::optional<Location> locArg = std::nullopt);
  void genRevert(TypeRange tys, ValueRange vals, StringRef signature,
                 std::optional<Location> locArg = std::nullopt);

  /// Generates a revert with values. (Useful for debugging)
  void genDbgRevert(ValueRange vals,
                    std::optional<Location> locArg = std::nullopt);

  /// Conditionally generates a revert with values. (Useful for debugging)
  void genCondDbgRevert(Value cond, ValueRange vals,
                        std::optional<Location> locArg = std::nullopt);
};

} // namespace evm
} // namespace mlir

#endif // MLIR_CONVERSION_SOLTOSTANDARD_EVMUTIL_H
